### ISSUE TITLE
--build-only leads to "IllegalStateException"

### ISSUE THREAD

**Issue by koppor** [uniba-dsg/betsy#47]
I'm trying to run `betsy-bpel.bat --build-only`. I have Apache Tomcat running on my machine. I expect betsy to generate BPEL files. Now, I get following output

```
[] [] Using VirtualBox version '5.0.6'
[] [] Disabling LinkUpDelay for this VirtualBox instance...
[0/5350] [] Deleting directory C:\git-repositories\betsy\test
[0/5350] [] Directory is already deleted!
[0/5350] [] Creating directory C:\git-repositories\betsy\test
[0/5350] [test] Creating directory C:\git-repositories\betsy
[0/5350] [test] Directory already there - skipping creation
[0/5350] [test] Start ...
[0/5350] [test] Checking whether the url http://localhost:8080 returns HTTP 200
[0/5350] [test] Got response code 200
[0/5350] [test] ... finished in 1s | (1234ms)
[0/5350] [betsy] something went wrong during execution
java.lang.IllegalStateException: Engine orchestra__4_9 is running
        at betsy.bpel.BPELComposite.lambda$execute$3(BPELComposite.java:55)
        at betsy.common.util.LogUtil.log(LogUtil.java:31)
        at betsy.common.util.LogUtil.log(LogUtil.java:58)
        at betsy.bpel.BPELComposite.log(BPELComposite.java:37)
        at betsy.bpel.BPELComposite.execute(BPELComposite.java:50)
        at betsy.bpel.BPELBetsy.execute(BPELBetsy.java:30)
        at betsy.bpel.BPELMain.main(BPELMain.java:74)
Unexpected exception thrown.
```

I don't know why a VirtualBox is started and why "orchestra" is said to be running.

**Comment by koppor** [comment]
For the record: The plain bpel files seem to be located at `src\main\tests\files\bpel`. Don't know, what `--build-only` is for. :innocent:

**Comment by matthiasgeiger** [comment]
This option creates the whole projects which are deployable for the respective engines - i.e., engine specific adaptions, building wars, etc.

**Comment by simonharrer** [comment]
Orchestra is marked as running as you have something running on port 8080 on your machine. Betsy requires that the ports used by each engine are not used, even on build-only mode. 

The reason why virtualbox is started is that we also test engines within virtual machines.

**Comment by lenhard** [comment]
Are we going to change something based on this issue? As far as I can see, betsy acts as desired. So can we close this?

**Comment by matthiasgeiger** [comment]
more or less... the one aspect to discuss is whether the check regarding running engines is required if `--build-only` is executed. 

Imho, I would leave this as is and close the issue.

**Comment by koppor** [comment]
@matthiasgeiger This is exactly my point.
