### ISSUE TITLE
add camunda 7.4.0

### ISSUE THREAD

**Issue by simonharrer** [uniba-dsg/betsy#49]

**Comment by lenhard** [comment]
Camunda 7.4.0 is not working on travis ci. From the log:
```
betsy.BPMNSystemTest > test_A_BpmnCamunda740SequenceFlow FAILED
    org.junit.ComparisonFailure: expected:<[[SequenceFlow;camunda__7_4_0;basics;1;0;1;1]]> but was:<[[]]>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at betsy.BPMNSystemTest.testBPMNEngine(BPMNSystemTest.java:94)
        at betsy.BPMNSystemTest.test_A_BpmnCamunda740SequenceFlow(BPMNSystemTest.java:69)
```
