### ISSUE TITLE
OpenEsb(2.2, 2.3, 2.3.1 ) installation error on windows(10)

### ISSUE THREAD

**Issue by ChristophBroeker** [uniba-dsg/betsy#53]
First i got the error dialog, that the given path isn't valid.

![error](https://cloud.githubusercontent.com/assets/1192378/13321160/9e242118-dbcd-11e5-82a9-57d39677b6eb.JPG)

I fixed these by replaycing the slash with a backslash in the state.xml.  But now i got this error message in the console output:
```
java.lang.IllegalArgumentException: the path C:\Users\Christoph\IdeaProjects\betsy\server\openesb__2_3\glassfish is no directory
	at betsy.common.tasks.FileTasks.assertDirectory(FileTasks.java:82)
	at betsy.bpel.engines.openesb.OpenEsbCLI.<init>(OpenEsbCLI.java:13)
	at betsy.bpel.engines.openesb.OpenEsbEngine.getCli(OpenEsbEngine.java:53)
	at betsy.bpel.engines.openesb.OpenEsbEngine.shutdown(OpenEsbEngine.java:68)
	at betsy.bpel.UniformProcessEngineManagementAPI.shutdown(UniformProcessEngineManagementAPI.java:67)
	at betsy.bpel.BPELComposite.lambda$shutdown$5(BPELComposite.java:103)
	at betsy.bpel.BPELComposite$$Lambda$54/19500263.run(Unknown Source)
	at betsy.common.util.LogUtil.log(LogUtil.java:31)
	at betsy.bpel.BPELComposite.log(BPELComposite.java:34)
	at betsy.bpel.BPELComposite.shutdown(BPELComposite.java:103)
	at betsy.bpel.BPELComposite.lambda$null$3(BPELComposite.java:97)
	at betsy.bpel.BPELComposite$$Lambda$38/29780195.run(Unknown Source)
	at betsy.common.util.LogUtil.log(LogUtil.java:31)
	at betsy.common.util.LogUtil.log(LogUtil.java:58)
	at betsy.bpel.BPELComposite.log(BPELComposite.java:38)
	at betsy.bpel.BPELComposite.lambda$executeProcess$4(BPELComposite.java:87)
	at betsy.bpel.BPELComposite$$Lambda$37/31188836.run(Unknown Source)
	at betsy.bpel.Retry.atMostThreeTimes(Retry.java:33)
	at betsy.bpel.BPELComposite.executeProcess(BPELComposite.java:87)
	at betsy.bpel.BPELComposite.lambda$null$0(BPELComposite.java:69)
	at betsy.bpel.BPELComposite$$Lambda$36/22433966.run(Unknown Source)
	at betsy.common.util.LogUtil.log(LogUtil.java:31)
	at betsy.common.util.LogUtil.log(LogUtil.java:58)
	at betsy.bpel.BPELComposite.log(BPELComposite.java:38)
	at betsy.bpel.BPELComposite.lambda$execute$1(BPELComposite.java:63)
	at betsy.bpel.BPELComposite$$Lambda$35/3762154.run(Unknown Source)
	at betsy.common.util.LogUtil.log(LogUtil.java:31)
	at betsy.common.util.LogUtil.log(LogUtil.java:58)
	at betsy.bpel.BPELComposite.log(BPELComposite.java:38)
	at betsy.bpel.BPELComposite.execute(BPELComposite.java:51)
	at betsy.bpel.BPELBetsy.execute(BPELBetsy.java:30)
	at betsy.bpel.BPELMain.main(BPELMain.java:75)
	at betsy.Main.main(Main.java:16)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
 ```

**Comment by matthiasgeiger** [comment]
Problem seems to be caused be JDKs which are too new...
 
Build crashes for me with the same exception - in the log the following statement can be found:
```
[1/1] [test/openesb__2_2/structured__Sequence/engine_install] [ant.exec] [2016-02-25 15:09:45.867]> No compatible jvm was found on the system
```
manuall installation also fails with an error message that a JDK5 oder 6 (!!) is required... 

So if you really want to execute those old OpenESB version you might try it again after installing such an old JDK - or trying to find a workaround to get the installer up and running with a newer JDK version.

**Comment by ChristophBroeker** [comment]
@matthiasgeiger Thank you for help.
I tried to run the engines with JDK6 and openesb 2.3 and 2.3.1 ran with JDK6. But openesb 2.2 didn't run with JDK6 and didn't run with highest version (1.5.0.22) of JDK5 too. With version 1.5.0.13 openesb 2.2 ran.
