### ISSUE TITLE
Timeout problems with jBPM execution

### ISSUE THREAD

**Issue by matthiasgeiger** [uniba-dsg/betsy#72]
I just tried to create a new Jenkins project - which checks out a clean betsy instance and tried running `clean runBPMN -Pargs="ALL PATTERNS"`, i.e., testing the workflow patterns on all BPMN engines.

However the run failed with the following stack trace:
```
[2/414] [betsy] something went wrong during execution
java.util.NoSuchElementException: There is no timeout with this given key.
	at betsy.common.timeouts.timeout.Timeouts.getTimeout(Timeouts.java:66)
	at betsy.common.timeouts.timeout.TimeoutRepository.getTimeout(TimeoutRepository.java:30)
	at betsy.common.tasks.FileTasks.deleteDirectory(FileTasks.java:51)
	at betsy.bpmn.engines.jbpm.JbpmInstaller.install(JbpmInstaller.java:18)
	at betsy.bpmn.engines.jbpm.JbpmEngine620.install(JbpmEngine620.java:30)
	at betsy.bpmn.BPMNComposite.lambda$install$53(BPMNComposite.java:128)
	at betsy.bpmn.BPMNComposite$$Lambda$24/1192672907.run(Unknown Source)
	at betsy.common.util.LogUtil.log(LogUtil.java:32)
	at betsy.common.util.LogUtil.log(LogUtil.java:61)
	at betsy.bpmn.BPMNComposite.log(BPMNComposite.java:33)
	at betsy.bpmn.BPMNComposite.install(BPMNComposite.java:128)
	at betsy.bpmn.BPMNComposite.lambda$executeProcess$49(BPMNComposite.java:96)
	at betsy.bpmn.BPMNComposite$$Lambda$17/817978763.run(Unknown Source)
	at betsy.common.util.LogUtil.log(LogUtil.java:32)
	at betsy.common.util.LogUtil.log(LogUtil.java:61)
	at betsy.bpmn.BPMNComposite.log(BPMNComposite.java:33)
	at betsy.bpmn.BPMNComposite.executeProcess(BPMNComposite.java:93)
	at betsy.bpmn.BPMNComposite.lambda$null$46(BPMNComposite.java:61)
	at betsy.bpmn.BPMNComposite$$Lambda$16/1948471365.run(Unknown Source)
	at betsy.common.util.LogUtil.log(LogUtil.java:32)
	at betsy.common.util.LogUtil.log(LogUtil.java:61)
	at betsy.bpmn.BPMNComposite.log(BPMNComposite.java:33)
	at betsy.bpmn.BPMNComposite.lambda$execute$47(BPMNComposite.java:55)
	at betsy.bpmn.BPMNComposite$$Lambda$15/873610597.run(Unknown Source)
	at betsy.common.util.LogUtil.log(LogUtil.java:32)
	at betsy.common.util.LogUtil.log(LogUtil.java:61)
	at betsy.bpmn.BPMNComposite.log(BPMNComposite.java:33)
	at betsy.bpmn.BPMNComposite.execute(BPMNComposite.java:46)
	at betsy.bpmn.BPMNBetsy.execute(BPMNBetsy.java:30)
	at betsy.bpmn.BPMNMain.main(BPMNMain.java:107)
```
@ChristophBroeker can you please investigate?

The full jenkins log is attached - some notes: In line 372/373 in the log it can be seen, that a single file could be not deleted in the previous test - this happens from time to time - but has not affected the test runs so far. 
In line 421/422 it is stated:
```
[2/414] [test/jbpm__6_2_0/cfpatterns__WCP09_Structured_Discriminator_ComplexGateway/engine_install] Deletion failed -> retrying after short wait
[2/414] [test/jbpm__6_2_0/cfpatterns__WCP09_Structured_Discriminator_ComplexGateway/engine_install] ... finished in 0s | (171ms)
```
This is related to the failed deletion - the file mentioned above is still locked and it requires some time for the lock to be released. However, the retry seems to fail with the exception above.

[jenkins.log.txt](https://github.com/uniba-dsg/betsy/files/267729/jenkins.log.txt)

**Comment by simonharrer** [comment]
@ChristophBroeker @matthiasgeiger is this fixed now?

**Comment by matthiasgeiger** [comment]
Should have been fixed with https://github.com/uniba-dsg/betsy/pull/73 - a run after this fix also succeeded sucessfully.
